//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AspNetUser
{
    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }
}

public partial class Content
{
    public int ContentID { get; set; }
    public Nullable<int> WebPageID { get; set; }
    public string EnContent { get; set; }
    public string LangContent { get; set; }
    public Nullable<bool> IsReachText { get; set; }

    public virtual WebPage WebPage { get; set; }
}

public partial class ContentImage
{
    public int ContentImageID { get; set; }
    public Nullable<int> WebPageID { get; set; }
    public string LangContent { get; set; }
    public string PicsUrl { get; set; }

    public virtual WebPage WebPage { get; set; }
}

public partial class Error
{
    public int Id { get; set; }
    public Nullable<System.DateTime> ErrorDate { get; set; }
    public string IpAddress { get; set; }
    public string UserAgent { get; set; }
    public string Exception { get; set; }
    public string Message { get; set; }
    public string Everything { get; set; }
    public string HttpReferer { get; set; }
    public string PathAndQuery { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public System.DateTime CreatedOn { get; set; }
    public Nullable<int> ChangedBy { get; set; }
    public System.DateTime ChangedOn { get; set; }
    public string FullURL { get; set; }
    public string UserName { get; set; }
    public string ErrorID { get; set; }
}

public partial class HeaderContent
{
    public int HeaderID { get; set; }
    public string HeaderName { get; set; }
    public string HeaderContent1 { get; set; }
}

public partial class WebPage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WebPage()
    {
        this.Contents = new HashSet<Content>();
        this.ContentImages = new HashSet<ContentImage>();
    }

    public int WebPageID { get; set; }
    public Nullable<int> PageNo { get; set; }
    public string PageName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Content> Contents { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ContentImage> ContentImages { get; set; }
}
