//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SoftSwitchDBEntities : DbContext
{
    public SoftSwitchDBEntities()
        : base("name=SoftSwitchDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    public virtual DbSet<Content> Contents { get; set; }
    public virtual DbSet<ContentImage> ContentImages { get; set; }
    public virtual DbSet<HeaderContent> HeaderContents { get; set; }
    public virtual DbSet<WebPage> WebPages { get; set; }
    public virtual DbSet<Error> Errors { get; set; }
}
